# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Union, Annotated  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator, StringConstraints  # noqa: F401

from uuid import UUID

class Catalog(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Catalog - a model defined in OpenAPI

        id: The id of this Catalog.
        name: The name of this Catalog.
        product_ids: The product_ids of this Catalog.
    """

    id: UUID = Field(alias="id")
    name: Annotated[str, StringConstraints(min_length=1, max_length=32)]
    product_ids: List[str] | None

    class Config:
        arbitrary_types_allowed = True

Catalog.update_forward_refs()
