# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401

from crm.openapi_server.models.connection_type import ConnectionType


class Connection(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Connection - a model defined in OpenAPI

        id: The id of this Connection.
        name: The name of this Connection [Optional].
        type_connection: The type_connection of this Connection.
        is_bot: The is_bot of this Connection.
        phone_number: The phone_number of this Connection.
    """

    id: object = Field(alias="id")
    name: Optional[object] = Field(alias="name", default=None)
    connection_type: ConnectionType = Field(alias="connection_type")
    is_bot: object = Field(alias="is_bot")
    phone_number: object = Field(alias="phone_number")

    class Config:
        arbitrary_types_allowed = True

    @validator("name")
    def name_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 32
        return value

    @validator("is_bot")
    def is_bot_max(cls, value):
        assert value <= 1
        return value

    @validator("is_bot")
    def is_bot_min(cls, value):
        assert value >= 0
        return value

    @validator("phone_number")
    def phone_number_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("phone_number")
    def phone_number_max_length(cls, value):
        assert len(value) <= 16
        return value

Connection.update_forward_refs()
