# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator, field_validator  # noqa: F401
from crm.openapi_server.models.customer import Customer


class Dialog(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Dialog - a model defined in OpenAPI

        id: The id of this Dialog [Optional].
        client: The client of this Dialog [Optional].
        connection_id: The connection_id of this Dialog [Optional].
        last_activity: The last_activity of this Dialog [Optional].
        amount_unread_msg: The amount_unread_msg of this Dialog [Optional].
    """

    id: Optional[object] = Field(alias="id", default=None)
    client: Optional[Customer] = Field(alias="client", default=None)
    connection_id: Optional[object] = Field(alias="connection_id", default=None)
    last_activity: Optional[object] = Field(alias="last_activity", default=None)
    amount_unread_msgs: Optional[object] = Field(alias="amount_unread_msgs", default=None)

    class Config:
        arbitrary_types_allowed = True

    @field_validator("amount_unread_msgs")
    def amount_unread_msg_min(cls, value):
        assert value >= 0
        return value

Dialog.update_forward_refs()
