# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class DialogMessage(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    DialogMessage - a model defined in OpenAPI

        id: The id of this DialogMessage [Optional].
        connection_id: The connection_id of this DialogMessage [Optional].
        messages: The messages of this DialogMessage [Optional].
        no_reply: The no_reply of this DialogMessage [Optional].
    """

    id: Optional[object] = Field(alias="id", default=None)
    connection_id: Optional[object] = Field(alias="connection_id", default=None)
    messages: Optional[object] = Field(alias="messages", default=None)
    no_reply: Optional[object] = Field(alias="no_reply", default=None)

    class Config:
        arbitrary_types_allowed = True

DialogMessage.update_forward_refs()
