# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from crm.openapi_server.models.type_resource import TypeResource


class Menu(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Menu - a model defined in OpenAPI

        id: The id of this Menu [Optional].
        name: The name of this Menu [Optional].
        resource: The resource of this Menu.
    """

    id: Optional[object] = Field(alias="id", default=None)
    name: Optional[object] = Field(alias="name", default=None)
    resource: TypeResource = Field(alias="resource")

    class Config:
        arbitrary_types_allowed = True

    @validator("name")
    def name_min_length(cls, value):
        assert len(value) >= 1
        return value

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 64
        return value

Menu.update_forward_refs()
