# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Message(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Message - a model defined in OpenAPI

        id: The id of this Message [Optional].
        dialog_id: The dialog_id of this Message.
        text: The text of this Message.
        _date: The _date of this Message.
    """

    id: Optional[object] = Field(alias="id", default=None)
    dialog_id: object = Field(alias="dialog_id")
    text: object = Field(alias="text")
    _date: object = Field(alias="date")

Message.update_forward_refs()
