# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional, Annotated  # noqa: F401
from uuid import UUID

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator, StringConstraints  # noqa: F401

from crm.openapi_server.models.product import Product


class NewCatalog(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    NewCatalog - a model defined in OpenAPI

        id: The id of this NewCatalog [Optional].
        name: The name of this NewCatalog.
        products: The products of this NewCatalog.
    """

    id: Optional[UUID] = None
    name: Annotated[str, StringConstraints(min_length=1, max_length=32)]
    products: List[Product] = []

    class Config:
        arbitrary_types_allowed = True


NewCatalog.update_forward_refs()
