# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from crm.openapi_server.models.connection import Connection
from crm.openapi_server.models.status_newsletter import StatusNewsletter


class Newsletter(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Newsletter - a model defined in OpenAPI

        id: The id of this Newsletter.
        name: The name of this Newsletter.
        connection: The connection of this Newsletter.
        text: The text of this Newsletter.
        date_run: The date_run of this Newsletter.
        client_ids: The client_ids of this Newsletter [Optional].
        tag_ids: The tag_ids of this Newsletter [Optional].
        status: The status of this Newsletter.
        received: The received of this Newsletter.
        readed: The readed of this Newsletter.
    """

    id: object = Field(alias="id")
    name: object = Field(alias="name")
    connection: Connection = Field(alias="connection")
    text: object = Field(alias="text")
    date_run: object = Field(alias="date_run")
    client_ids: Optional[object] = Field(alias="clientIds", default=None)
    tag_ids: Optional[object] = Field(alias="tagIds", default=None)
    status: StatusNewsletter = Field(alias="status")
    received: object = Field(alias="received")
    readed: object = Field(alias="readed")

    class Config:
        arbitrary_types_allowed = True

    @validator("name")
    def name_max_length(cls, value):
        assert len(value) <= 64
        return value

    @validator("text")
    def text_max_length(cls, value):
        assert len(value) <= 4096
        return value

    @validator("received")
    def received_min(cls, value):
        assert value >= 0
        return value

Newsletter.update_forward_refs()
