# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class Note(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Note - a model defined in OpenAPI

        id: The id of this Note [Optional].
        customer_id: The customer_id of this Note [Optional].
        note: The note of this Note.
        _date: The _date of this Note.
    """

    id: Optional[str] = Field(alias="id", default=None)
    customer_id: Optional[str] = Field(alias="customer_id", default=None)
    note: str = Field(alias="note")
    date: datetime = Field(alias="date")

Note.update_forward_refs()
