# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class PatchUsersUserIdRequest(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    PatchUsersUserIdRequest - a model defined in OpenAPI

        first_name: The first_name of this PatchUsersUserIdRequest [Optional].
        last_name: The last_name of this PatchUsersUserIdRequest [Optional].
        email: The email of this PatchUsersUserIdRequest [Optional].
        date_of_birth: The date_of_birth of this PatchUsersUserIdRequest [Optional].
    """

    first_name: Optional[str] = Field(alias="firstName", default=None)
    last_name: Optional[str] = Field(alias="lastName", default=None)
    email: Optional[str] = Field(alias="email", default=None)
    date_of_birth: Optional[str] = Field(alias="dateOfBirth", default=None)

PatchUsersUserIdRequest.update_forward_refs()
