# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from enum import Enum
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401
from crm.openapi_server.models.connection import Connection
from crm.openapi_server.models.status_subscription import StatusSubscription


class Subscription(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Subscription - a model defined in OpenAPI

        id: The id of this Subscription.
        status: The status of this Subscription.
        connection: The connection of this Subscription.
        until_valid: The until_valid of this Subscription.
        included_subscribe: The included_subscribe of this Subscription.
    """

    id: object = Field(alias="id")
    status: StatusSubscription = Field(alias="status")
    connection: Connection = Field(alias="connection")
    until_valid: datetime = Field(alias="until_valid")
    included_subscribe: bool = Field(alias="included_subscribe")

    class Config:
        arbitrary_types_allowed = True

Subscription.update_forward_refs()
