# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class TypeResource(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TypeResource - a model defined in OpenAPI

        name: The name of this TypeResource [Optional].
        code: The code of this TypeResource.
    """

    name: Optional[object] = Field(alias="name", default=None)
    code: object = Field(alias="code")

    class Config:
        arbitrary_types_allowed = True

TypeResource.update_forward_refs()
