# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class TypeTerminal(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TypeTerminal - a model defined in OpenAPI

        sber_bank: The sber_bank of this TypeTerminal [Optional].
        pay_me: The pay_me of this TypeTerminal [Optional].
        click: The click of this TypeTerminal [Optional].
    """

    sber_bank: Optional[object] = Field(alias="SberBank", default=None)
    pay_me: Optional[object] = Field(alias="PayMe", default=None)
    click: Optional[object] = Field(alias="Click", default=None)

TypeTerminal.update_forward_refs()
