# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class User(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    User - a model defined in OpenAPI

        id: The id of this User.
        first_name: The first_name of this User.
        last_name: The last_name of this User.
        email: The email of this User.
        date_of_birth: The date_of_birth of this User [Optional].
        email_verified: The email_verified of this User.
        create_date: The create_date of this User [Optional].
        : The  of this User [Optional].
    """

    id: object = Field(alias="id")
    first_name: object = Field(alias="firstName")
    last_name: object = Field(alias="lastName")
    email: object = Field(alias="email")
    date_of_birth: Optional[object] = Field(alias="dateOfBirth", default=None)
    email_verified: object = Field(alias="emailVerified")
    create_date: Optional[object] = Field(alias="createDate", default=None)

    class Config:
        arbitrary_types_allowed = True

User.update_forward_refs()
